### PR TITLE
additional whitespace

### PR DESCRIPTION
**Pull request by SamuelPlentz**

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks for your contributions! However, I will reject this one: The entire wiki is using the notation without spaces. I will keep it as it is.

**Comment by SamuelPlentz** [comment]
Did you mention, that I removed the whitespace? My comment should have been "additional whitespace removed" instead of "additional whitespace", sorry.
German is also the only language that uses the untranslated `[[TO = firstname]]`.

Current situation:
`en-US\messages.json: "message": "... variables like [[TO=firstname]] ..."`
`de\messages.json: "message": "... Variablen wie [[TO = firstname]] ..."`
`hu\messages.json: "message": "... beleértve a [[Címzett=Keresztnév]] ..."`
`fr\messages.json: "message": "... variables telles que [[TO = prénom]]."`
`es\messages.json: "message": "... variables como [[TO = nombre]] ..."`
`ru\messages.json: "message": "... категории (групп контактов, основанных на категории)."`

Should we change it to this: (3x whitespace removed; German translated)
`en-US\messages.json: "message": "... variables like [[TO=firstname]] ..."`
`de\messages.json: "message": "... Variablen wie [[TO=Vorname]] ..."`
`hu\messages.json: "message": "... beleértve a [[Címzett=Keresztnév]] ..."`
`fr\messages.json: "message": "... variables telles que [[TO=prénom]]."`
`es\messages.json: "message": "... variables como [[TO=nombre]] ..."`
`ru\messages.json: "message": "... категории (групп контактов, основанных на категории)."`

or to that: (3x whitespace removed; revert translation of others)
`en-US\messages.json: "message": "... variables like [[TO=firstname]] ..."`
`de\messages.json: "message": "... Variablen wie [[TO=firstname]] ..."`
`hu\messages.json: "message": "... beleértve a [[TO=firstname]] ..."`
`fr\messages.json: "message": "... variables telles que [[TO=firstname]]."`
`es\messages.json: "message": "... variables como [[TO=firstname]] ..."`
`ru\messages.json: "message": "... категории (групп контактов, основанных на категории)."`

**Comment by jobisoft** [comment]
Oh my, I was reading this on a mobile device and missread this.

Yes, remove those whitespaces wherever you find one and always use TO=firstname as both are technical terms (TO and firstname) and must not be translated. 


Thanks for your help! You can simply commit to your working branch of this pull request to update this pull request.

**Comment by SamuelPlentz** [comment]
IMO ready. Updated de, es, fr, hu and pt_BR

**Comment by jobisoft** [comment]
Thanks!

**Pull request merged**
