### PR TITLE
fixing issues

### PR DESCRIPTION
**Pull request by jobisoft**
fixing issue #12 and #13

### CODE REVIEW

**Comment by lieser** [comment]
Thanks a lot for the quick fix.

**Comment by jobisoft** [comment]
you can set a release/tag for v1.1, if you like.

**Comment by jobisoft** [comment]
@kewisch Rejected 1.1 because auf 

```
thread.processNextEvent()
```

**Comment by jobisoft** [comment]
Sorry, erosman rejected, because of a comment by @kewisch to version 1.0

Reviewer:
erosman

Comments:
This version did not pass the review because of the following issues:

1) Issues listed on the previous reviews are still outstanding.

By Philipp Kewisch on June 1, 2018
"For future versions, please remove use of thread.processNextEvent() for stability reasons. Using this to spin the event loop to make an async function synchronous is known to cause crashes."

components/wzQuicktext.js#L684
components/wzQuicktextVar.js#L834, 985

**Comment by jobisoft** [comment]
Thanks @kewisch. He has allowed v1.1 to pass review. We have till TB61 to get the lazy async-to-sync code replaced.

**Pull request merged**
