### PR TITLE
Reading UTF-8 files with Umlaut fixed

### PR DESCRIPTION
**Pull request by kicktipp**
> Just to rule out any misunderstanding: I know that reading of utf8 files worked before. I mentioned that here: #22 (comment)

But it worked only for UTF-8 files which had only 1 byte characters. It did not worked for UTF-8 with umlaut as they are encoded with two bytes.

### CODE REVIEW

**Comment by jobisoft** [comment]
This problem is deeper. At the moment I cannot make everybody happy. Those who currently have ISO 8859-1 set as their default/system encoding, everything works fine. If I merge this PR, I will break quicktext for all these people.

For importing XML, we could actually parse the XML encoding field to get the encoding requested by the user:

`<?xml version="1.0" encoding="ISO-8859-1"?>`

But quicktext also allows to import plain text files which are merged into the document and besides the utf16 dom header, there is no known method to detect the encoding of a document. So I am stuck at the moment and need to think about this. What are our options?

**Comment by jorgk3** [comment]
Some drive-by comments:
Windows uses windows-1252 (and similar) as system charset, not ISO-8859-1 (and similar).

> there is no known method to detect the encoding of a document

Um, surely to can at least detect valid UTF-8:
[IsUTF8](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/xpcom/string/nsReadableUtils.h#631)
You can also detect Latin-1 (windows1252):
[IsUTF8Latin1](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/xpcom/string/nsReadableUtils.h#569)
Sure, that's C++ code, you'd have to find/code an equivalent in JS.

In any case you can prevent windows-1252 being interpreted as (invalid) UTF-8.

**Comment by jobisoft** [comment]
Thanks @jorgk3 , I was about to ask for your feedback. The issue creator is using ISO-8859-2, is that also detectable or will this end up in guessing? I did not yet look at the code you linked ...

What do you think about going for the XML encoding field for XML reads (at application start, during import, etc.)? Also, have to check, but I think the other plain text import only happens by user interaction, so we could actually ask the user for the charset, by presenting a selection box or something.

**Comment by jorgk3** [comment]
Hmm, ISO-8859-2 is Latin-2 or "Eastern European". You can really only check valid UTF-8. Other than that, yes, I'd process the encoding information where available.

Off topic: Boy, this add-on is creating such a lot of comments, it must be the most popular add-on of all times :wink:

**Comment by jobisoft** [comment]
After another read-the-doc session I know the following:

1. The current version of fix_fileformat is broken, because the "new" utf-8 config files without BOM are currently read by [nsIScriptableInputStream](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIScriptableInputStream#read()) which simply assumes ISO-Latin-1 encoding. So after saving and restarting TB, all special chars in the templates are messed up.

2. This PR actually fixes that.

3. This PR overshoots by enforcing utf-8 for all read files, not just the config XML files. That might break stuff.

I need some rest now.

**Comment by jobisoft** [comment]
I found an easy solution for the "Is-UTF-8" check: I just assume it is UTF and wrap the nsIScriptableUnicodeConverter in a try ... catch and fall back to the ISO-Latin-1 decoded string, if that failed. 

That keeps the old behavior and allows to import ISO-Latin-1 encoded files, but now also allows to import UTF-8 encoded files.

**Comment by kicktipp** [comment]
Great work! Please make a release soon if possible. I hope my patch was of any help. Sadly you deleted the .gitignore file which I find very helpful. But doesn't matter too much. Thanks a lot for keeping quicktext running. This is our most valuable tool in our tool chain.

**Pull request merged**
