### PR TITLE
CSS changes for toolbar buttons

### PR DESCRIPTION
**Pull request by SamuelPlentz**
see issue #172 (TB78 : Menu entries missing an dropdown arrow)

### CODE REVIEW

**Comment by jobisoft** [comment]
So this patch applies to the fixed version I published in the issue? Have I committed that change the repo? If not, could you include that in your PR? I have no time at the moment.

**Comment by SamuelPlentz** [comment]
Looks a little bit like the dropdown branch here in the repository.
You added a zip file [here](https://github.com/jobisoft/quicktext/issues/172#issuecomment-691537296_).

**Comment by jobisoft** [comment]
I hope I merged the correct parts, could you check if the TB78 branch is now working as intended?

**Comment by SamuelPlentz** [comment]
Looks correct. Could not find any problems. CSS and white space is correct.

**Pull request merged**
