### PR TITLE
Fix linenumber offset; translate messages

### PR DESCRIPTION
**Pull request by SamuelPlentz**
The previous linenumber offset was wrong. Probably other commits changed the line. Should be future proof.
Translated debug messages.

Could you please verify the English text before I copy it to the other locales?

### CODE REVIEW

**Comment by jobisoft** [comment]
Whoops. Good catch.

If you add locale strings, you need to add them to all locales, otherwise you break quicktext for users of those other locales.

**Comment by jobisoft** [comment]
> Could you please verify the English text before I copy it to the other locales?

Did not see that, hold on.

**Comment by SamuelPlentz** [comment]
> If you add locale strings, you need to add them to all locales, otherwise you break quicktext for users of those other locales.

I am aware of that.

See here:
> Could you please verify the English text before I copy it to the other locales?

**Comment by SamuelPlentz** [comment]
IMO we should change it, so a missing string is taken from the english translation...

**Comment by jobisoft** [comment]
:-) I saw that like 2 seconds before your post (see my last comment). Reviewing...

**Comment by jobisoft** [comment]
> IMO we should change it, so a missing string is taken from the english translation...

You would need to file a bug at thunderbird for that, but it will probably be discarded as with TB74 the locale system is changing altogether.

**Comment by SamuelPlentz** [comment]
Fluent, IIRC.

**Comment by jobisoft** [comment]
My suggestion:

de: In Ihrem Skript ist ein Fehler aufgetreten:
en: There was an error in your script:

**Comment by SamuelPlentz** [comment]
Thanks better text. I strictly translated the existing text from the `.js` file.

Done.

Used `Quicktext script` like the scriptNotFound did.

**Comment by jobisoft** [comment]
One final nitpick: In your inline comments, you do not need to reference old code, just comment on what the current code is doing. If you want to add such "I changed it from this to that" comments, you can add them to the commit itself.

**Comment by SamuelPlentz** [comment]
Thanks for the heads up.

Done.

**Pull request merged**
