### PR TITLE
fix #19 Use whole editor as range when replace [[CURSOR]] tag

### LINKED ISSUE #19: Bug: [CURSOR] tag not working in MacOS in TB 52.9.1
I do not know, why the CURSOR tag is not working. This is a bug.

### PR DESCRIPTION
**Pull request by vsantana**

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks for your work! I will check this on Monday.

**Comment by Siflei** [comment]
Any chance, that [[CURSOR]] will work again?

**Comment by jobisoft** [comment]
The above fix is only working/needed for Mac on TB 52.9. There is no fix avail yet for TB 60.

**Comment by jorgk3** [comment]
I keep getting e-mail about this CURSOR problem. The code does this:
while ((foundRange = finder.Find("[[CURSOR]]", aSearchRange, startRange, endRange)) != null)
https://github.com/thundernest/quicktext/blob/73ff720353ce1e408047a50db9915ceb46761a0c/chrome/content/quicktext.js#L559

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c48 the behaviour of .Find() seems to have changed. Lot's of changes in the M-C file:
https://hg.mozilla.org/mozilla-central/log/tip/toolkit/components/find/nsFind.cpp
but the basic function should still work since it's tested in the Mozilla test suite:
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/windowcreator/test/test_nsFind.html

So either look for changes in the log of nsFind.cpp or make sure that the parameters are correct.

**Comment by jobisoft** [comment]
Closing, as this fix does not solve the problem and we have a promising candidate in PR # 43. Thank you for your work on this topic.

**Pull request closed without merging**
