### PR TITLE
allow the use of CDATA end tokens

### PR DESCRIPTION
**Pull request by SamuelPlentz**
Allow to use ```]]>``` - fixes issue #324

### CODE REVIEW

**Comment by jobisoft** [comment]
Holy cow. I will think about this. Thanks for your research!

**Comment by SamuelPlentz** [comment]
Got closed accidentially.

**Comment by jobisoft** [comment]
Let's give this a try.

**Comment by jobisoft** [comment]
Please verify:
https://github.com/jobisoft/quicktext/releases/tag/v5.6

**Comment by SamuelPlentz** [comment]
I can confirm, that this is fixed in version 5.6.

**Pull request merged**
