### PR TITLE
Add image src inline with base64

### PR DESCRIPTION
**Pull request by PhoneixS**
Add a new variable which can add a base64 encoded content that can be inserted instead of a path in a img src attribute.

It could be improved but rigth now can be used as it is.

Ref #52

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks for your contribution. Could you add the new locales to all languages? Otherwise it will break for them. No need to translate, just use the english text, but the keys must be present.

**Comment by PhoneixS** [comment]
Yes! I forgot. Also I will translate it to Spanish.

**Comment by PhoneixS** [comment]
I have added the documentation of the IMAGE variable to the [wiki page](https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags).

**Comment by jobisoft** [comment]
Perfect. Thanks!

I will do a functional test in the next few days and merge it afterwards. Can you describe in a few sentences, what I should do and what I should expect to happen?

**Comment by PhoneixS** [comment]
You should try to read a file (as with the file function) but instead of inserting the content as text it should encode it as a base64 image.

You could use the Wikipedia example but with a file name:

```
<img src="data:image/png;filename=Red-dot-5px.png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot" />
```
Note that the output of the variable / function is only the part in src:

```
data:image/png;filename=Red-dot-5px.png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==
```

The function should recognize the data type ("image/png" in this case) from the extension of the file name and also include the name in the "filename" parameter.

The image file can be downloaded from https://upload.wikimedia.org/wikipedia/commons/3/31/Red-dot-5px.png (is in the public domain).

**Comment by jobisoft** [comment]
Tested it and it works as you described. If you still have a little bit of time, I would like to ask for the following changes:

_1a. Not only add the src but add the entire img tag.
1b. Allow to specify the alternatve text as second parameter_

So

```
[[IMAGE=path\to\Red-dot-5px.png|Red dot]]
```

will be replaced by:

```
<img src="data:image/png;filename=Red-dot-5px.png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot" />
```

This will make it usable also for unskilled users.  And also

_2. If the template is not added as HTML, insert a warning instead of the image tag, as the src in plain text will slow down TB a lot and it is clearly not useful._

What do you think? I would do it myself, but I am totally booked. I really appreciate your work on this and I am sorry for asking for more.

**Comment by PhoneixS** [comment]
I have also thought about making it for the full tag but I see that at least in my use case I would need to add many attributes (alt, width, height, style) so I opt in for the easy way as I don't have more time to do it. I could try to do it next year. 

About point 2 I don't really know how to do it. This is the first time I develop for thunderbird.

**Comment by jobisoft** [comment]
Understood. Your use case shows my proposal is bad. I will try to impl. the second suggestion.

**Comment by jobisoft** [comment]
I need to circle back to this. I want the default behavior of the IMAGE tag to insert the entire html image tag, which will be needed by most users. However, by specifying a second parameter "src", only the src attribute will be inserted (as now).

So you need to change your scripts and add the "src" keyword:

```
[[image=filename|src]]
```

to keep your scripts working when the new version is released. The parameter is a NoOp in the current release.

**Comment by PhoneixS** [comment]
I think it's a good idea that for the default to be the full tag, as I also think the average user would want to use as that and having an option to have only the content is a good way for more advanced users to achieve what they want.

**Pull request merged**
