### PR TITLE
Fix issue 307 (HEADER) for TB 102

### PR DESCRIPTION
**Pull request by SamuelPlentz**

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks. Do you have a paypal donate account?

**Comment by SamuelPlentz** [comment]
I am really blessed in my life and have everything I need. Thanks for the question though.

**Comment by jobisoft** [comment]
Uuups, can you file this again against the 102 branch?

**Comment by SamuelPlentz** [comment]
Hope #312 works.

**Pull request merged**
