### PR TITLE
update german translation

### PR DESCRIPTION
**Pull request by SamuelPlentz**
Perhaps the Text of other languages should also be changed to
`<!ENTITY quicktext.image.label "HTML-image src (base64 encoded)">`

### CODE REVIEW

**Comment by jobisoft** [comment]
The header is indeed called TO, it is a technical description. Will need to thin about this.

**Comment by SamuelPlentz** [comment]
I also was unsure if it should be translated or treated as a technical term. IMO one should prefer the non technical term, when in doubt. But I am fine if this in not changed.

What do you think about the other change?

**Comment by jobisoft** [comment]
Let me first evaluate your other suggestion regarding the image tag inserting the entire img tag and not just the source, which would req. a different label altogether.

**Comment by jobisoft** [comment]
I want to keep the technical header names. 

The image tag has been updated and now inserts the entire html image tag (and optional just the base64 src attribute). So `quicktext.image.label` must be updated. Do you want to use this PR to take care of this? Otherwise just close this PR and I will update the locale files.

Thanks for your input and your contributions!

**Comment by jobisoft** [comment]
"Insert HTML image" / "HTML-Bild einfügen" would be enough, the optional base64 src mode does not need to be mentioned, I guess.

**Comment by SamuelPlentz** [comment]
Will update.

What do you think about adding the word `inline` as well?
`Insert inline HTML image`

**Comment by jobisoft** [comment]
Yeah, was thinking the same, either inline or embedded. I am not an english native so I am not entirely sure, but I would tend to use embedded.

**Comment by SamuelPlentz** [comment]
Should be fine now.

**Comment by jobisoft** [comment]
Could you make the first letter "e" in all locales upper case?

**Comment by SamuelPlentz** [comment]
Done.

**Pull request merged**
