### PR TITLE
Use ID of quicktext in quicktext pro, preparing to replace standard version with pro version

### PR DESCRIPTION
**Pull request by jobisoft**
Also remove hesslow URL and support for Postbox (whih no longer supports addons).

I also ask for permission to remove hesselow URL from the AMO page, because he does not provide any support but still takes donations, which is kind of not nice. There is a forum on hesselow, but I would abondon that as well and use the github issue section for user interaction or create a thread in https://support.mozilla.org?

After pulling this, can you remove the "amo" branch and rename the "master" branch to "standard"?

### CODE REVIEW

**Comment by lieser** [comment]
You can remove the hesselow URL from the AMO page, and let it point to GitHub instead. Is it intentional that you left the  http://extensions.hesslow.se/quicktext URL in `chrome/content/about.xul` and `components/wzQuicktext.js`?

As for user interaction: issues on GitHub would be fine for us. Note however that we (the TB council) do currently not intent to provide any big support for the add-on. So maybe additionally creating a thread on https://discourse.mozilla.org/c/thunderbird would help the add-on user to support each other.
As for the https://support.mozilla.org site: I don't think that site is intended/used for any kind of support for specific add-ons.

There should probably still be links somewhere to the _Getting Started_, _All Tags_, _Script Support_ and _Sharing Templates_ sites on http://extensions.hesslow.se/extension/5/Quicktext+Pro/ until there is at least some documentation on GitHub.

**Comment by jobisoft** [comment]
Valid points. I will fix the leftover URLs, did not see them.

For the documentation on github: A simple readme or doc/ folder which I can push via PR, or should we use the wiki feature? For the wiki, I think I need write access to the repository, because until now I was not able to make PR for a wiki.

**Comment by lieser** [comment]
Removed the write restriction on the wiki. Please let me know if you still can not create one.

**Comment by jobisoft** [comment]
Yes, I was able to create the wiki. I added the first two pages. Could you check, if I can continue like that?

**Comment by jobisoft** [comment]
URL stuff fixed by removing the about box.

**Comment by jobisoft** [comment]
You can merge. I still have to create a PR for the standard/master branch to update the readme there as well (or you could just copy the new one from the pro branch)

If I ever get the pro version running (with all the pro features) and release it to all the current quicktext users, should we keep the "pro" in the name, or should we just stick with "quicktext"? I prefer the later...

**Comment by lieser** [comment]
I will copy the readme to the standard/master branch.

On the naming:  I would also prefer to just name it quicktext in case we completely replace the current standard version with the pro version.

**Comment by lieser** [comment]
readme updated, and also did the requested branch changes.

**Comment by jobisoft** [comment]
Thanks, but I made a typo  - it is now in both readme files: In the last sentence, it is "des_c_ription", I left out the c. If you could just ... that will be all for today. :-)

**Pull request merged**
