### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by jobisoft**
1. Remove browserAction button, as I think it is wrong there. It should be in the composer only. Space is limited.
2. Use the new Icon-Only Mode for ComposeAction. The icon should be enough. Space is limited..

### CODE REVIEW

**Comment by jobisoft** [comment]
@SamuelPlentz : What do you think? 

image

**Comment by SamuelPlentz** [comment]
I agree, that its probably better to remove the text.
I use the icon in the browser window regularly when testing or editing profiles without writing an email. And as everyone can disable the icons in the place he doesn't need them, I would vote to keep it.

**Comment by jobisoft** [comment]
> I would vote to keep it.

If we keep it, can I remove the label there as well?

**Comment by SamuelPlentz** [comment]
No Text is fine for me.
Perhaps we should consider to keep the text. I just opened the Thunderbird toolbar settings. There is the possibility to show:

1. symbol and text below
2. symbol only
3. text only
4. symbol and text to the right

Especially when 1 or 3 is used, it would probably look strange.

**Comment by jobisoft** [comment]
I took care of that when adding the new icon only mode to the Thunderbird WebExtension API. If the user selects text only, the title is used (as before). Otherwise it behaves like the icon of the hamburger menu.

**Comment by SamuelPlentz** [comment]
In that case go ahead.

**Pull request merged**
