### PR TITLE
feat(tag): add monthname tag

### PR DESCRIPTION
**Pull request by drakulis**
Added `DATE=monthname` tag to insert month name in the template.

**Motivation**
I had to frequently send emails where I have to put current month in the email title and body. It is something like:
**Title**: Invoice for January
**Body**: Dear customer, please find enclosed invoice for January...

### CODE REVIEW

**Comment by jobisoft** [comment]
This slipped through, did not see it. Will look at it shortly!

**Comment by jobisoft** [comment]
Merging. Can you update the doc in the wiki? Thanks!

**Comment by drakulis** [comment]
Done

**Comment by jobisoft** [comment]
v1.3 is avail on ATN already (that was fast). Sorry for the long delay.

**Pull request merged**
