### PR TITLE
f4 keywordKey

### PR DESCRIPTION
**Pull request by stabledave**

### CODE REVIEW

**Comment by jobisoft** [comment]
Just a generall question: Is the F4 key somehow special? It kinda sticks out. Why not add all F keys? Are the other F Keys hardlinked to system calls and F4 the only one which could be used? 

I think - if possible - I would like to add as many F keys as possible in this PR. Otherwise everybody will ask, why is F4 allowed, but not the others?

FYI: You can simply continue to push into your branch and it will be automatically part of this PR. You may have to pull first, as I fixed whitespaces.

**Comment by stabledave** [comment]
> 
> 
> Just a generall question: Is the F4 key somehow special? It kinda sticks out. Why not add all F keys? Are the other F Keys hardlinked to system calls and F4 the only one which could be used?
> 
 
I chose F4 for my old ext because it's easy to reach while typing and F1-3 were bound to help, something I forgot (appearently in 68 now free again) and search. Upper F keys also have different core features bound. I'll commit the unbound F keys tomorrow.

**Comment by jobisoft** [comment]
I would like to merge this soon. What is your status? Thanks for your contribution!

**Comment by stabledave** [comment]
finished, just didn't commit yet. Will do when I come home later

**Pull request merged**
